# install.packages("tidyverse")
# install.packages("ggplot2")
# install.packages("tidymodels")
# install.packages("skimr")
# install.packages("janitor")
# install.packages("rmarkdown")
 library(tidyverse)
 library(ggplot2)
 library(tidymodels)
 library(skimr)
 library(janitor)
 library(rmarkdown)
olympics<-read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/olympics.csv')


